/* Generated by the Nim Compiler v2.0.2 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI184549391 = {size: 0,kind: 36,base: null,node: null,finalizer: null};
var NTI184549387 = {size: 0,kind: 34,base: null,node: null,finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI1056964614 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555173 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555183 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI687865937 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554445 = {size: 0,kind: 36,base: null,node: null,finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI1040187401 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI1040187401 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "x", len: 0, typ: NTI33554435, name: "x", sons: null}, 
{kind: 1, offset: "y", len: 0, typ: NTI33554435, name: "y", sons: null}, 
{kind: 1, offset: "opacity", len: 0, typ: NTI33554445, name: "opacity", sons: null}]};
NTI1040187401.node = NNI1040187401;
var NNI687865937 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI687865937.node = NNI687865937;
var NNI33555183 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555183.node = NNI33555183;
var NNI33555173 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555173.node = NNI33555173;
NTI33555183.base = NTI33555173;
NTI687865937.base = NTI33555183;
NTI1040187401.base = NTI687865937;
var NNI1056964614 = {kind: 2, len: 10, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "fill", len: 0, typ: NTI33554450, name: "fill", sons: null}, 
{kind: 1, offset: "pointerDirection", len: 0, typ: NTI33554450, name: "pointerDirection", sons: null}, 
{kind: 1, offset: "pointerWidth", len: 0, typ: NTI184549387, name: "pointerWidth", sons: null}, 
{kind: 1, offset: "pointerHeight", len: 0, typ: NTI184549387, name: "pointerHeight", sons: null}, 
{kind: 1, offset: "lineJoin", len: 0, typ: NTI33554450, name: "lineJoin", sons: null}, 
{kind: 1, offset: "shadowColor", len: 0, typ: NTI33554450, name: "shadowColor", sons: null}, 
{kind: 1, offset: "shadowBlur", len: 0, typ: NTI184549387, name: "shadowBlur", sons: null}, 
{kind: 1, offset: "shadowOffsetX", len: 0, typ: NTI184549387, name: "shadowOffsetX", sons: null}, 
{kind: 1, offset: "shadowOffsetY", len: 0, typ: NTI184549387, name: "shadowOffsetY", sons: null}, 
{kind: 1, offset: "shadowOpacity", len: 0, typ: NTI184549391, name: "shadowOpacity", sons: null}]};
NTI1056964614.node = NNI1056964614;
NTI1056964614.base = NTI687865937;

function toJSStr(s_33556901) {
  var result_33556902 = null;

    var res_33556943 = newSeq_33556919((s_33556901).length);
    var i_33556944 = 0;
    var j_33556945 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556944 < (s_33556901).length)) break Label2;
          var c_33556946 = s_33556901[i_33556944];
          if ((c_33556946 < 128)) {
          res_33556943[j_33556945] = String.fromCharCode(c_33556946);
          i_33556944 += 1;
          }
          else {
            var helper_33556959 = newSeq_33556919(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556960 = c_33556946.toString(16);
                  if ((((code_33556960) == null ? 0 : (code_33556960).length) == 1)) {
                  helper_33556959.push("%0");;
                  }
                  else {
                  helper_33556959.push("%");;
                  }
                  
                  helper_33556959.push(code_33556960);;
                  i_33556944 += 1;
                  if ((((s_33556901).length <= i_33556944) || (s_33556901[i_33556944] < 128))) {
                  break Label3;
                  }
                  
                  c_33556946 = s_33556901[i_33556944];
                }
            };
++excHandler;
            try {
            res_33556943[j_33556945] = decodeURIComponent(helper_33556959.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556943[j_33556945] = helper_33556959.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556945 += 1;
        }
    };
    if (res_33556943.length < j_33556945) { for (var i = res_33556943.length ; i < j_33556945 ; ++i) res_33556943.push(null); }
               else { res_33556943.length = j_33556945; };
    result_33556902 = res_33556943.join("");

  return result_33556902;

}
var F = {procname: "module macros", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module hashes", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/pure/hashes.nim", line: 0};
framePtr = F;
F.line = 218;
F.filename = "hashes.nim";
var objectID_738197681 = [0];
framePtr = F.prev;
var F = {procname: "module hashes", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/pure/hashes.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module outparams", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/std/outparams.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module outparams", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/std/outparams.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/pure/collections/tables.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/pure/collections/tables.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsffi", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/js/jsffi.nim", line: 0};
framePtr = F;
F.line = 45;
F.filename = "jsffi.nim";
F.line = 46;
framePtr = F.prev;
var F = {procname: "module jsffi", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/js/jsffi.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module dom", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/js/dom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module dom", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/js/dom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module shape", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/shapes/shape.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module shape", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/shapes/shape.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module group", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/shapes/group.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module group", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/shapes/group.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module circle", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/shapes/circle.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module circle", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/shapes/circle.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module rect", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/shapes/rect.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module rect", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/shapes/rect.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module text", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/shapes/text.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module text", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/shapes/text.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tag", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/shapes/tag.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tag", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/shapes/tag.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module label", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/shapes/label.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module label", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/shapes/label.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module line", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/shapes/line.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module line", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/shapes/line.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module arrow", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/shapes/arrow.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module arrow", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/shapes/arrow.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module layer", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/layer/layer.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module layer", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/layer/layer.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module stage", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/stage/stage.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module stage", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/stage/stage.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module converters", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/common/converters.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module converters", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/common/converters.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module konva", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/konva.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module konva", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/konva.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function newSeq_33556919(len_33556921) {
  var result_33556922 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 631;
    F.filename = "system.nim";
    result_33556922 = new Array(len_33556921); for (var i = 0 ; i < len_33556921 ; ++i) { result_33556922[i] = null; }  framePtr = F.prev;

  return result_33556922;

}

function newStage_1107296270(container_1107296271, width_1107296272, height_1107296273) {
  var result_1107296274 = null;

  var F = {procname: "stage.newStage", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/stage/stage.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 14;
    F.filename = "stage.nim";
    var options_1107296275 = {};
    F.line = 15;
    options_1107296275["container"] = toJSStr(container_1107296271);
    F.line = 16;
    options_1107296275["width"] = ((width_1107296272) | 0);
    F.line = 17;
    options_1107296275["height"] = ((height_1107296273) | 0);
    F.line = 18;
    result_1107296274 = new Konva.Stage(options_1107296275);
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_1107296274;

}

function toFloat_33556008(i_33556009) {
  var result_33556010 = 0.0;

  var F = {procname: "system.toFloat", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 1292;
    F.filename = "system.nim";
    result_33556010 = i_33556009;
  framePtr = F.prev;

  return result_33556010;

}

function HEX2F_33556020(x_33556021, y_33556022) {
  var result_33556023 = 0.0;

  var F = {procname: "system./", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 1340;
    F.filename = "system.nim";
    result_33556023 = (toFloat_33556008(x_33556021) / toFloat_33556008(y_33556022));
  framePtr = F.prev;

  return result_33556023;

}

function createTriangle_536870918(context_536870919, shape_536870920) {
  var F = {procname: "ex01_shapes.createTriangle", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/examples/ex01_shapes.nim", line: 0};
  framePtr = F;
    F.line = 8;
    F.filename = "ex01_shapes.nim";
    context_536870919.beginPath();
    F.line = 9;
    context_536870919.moveTo(20, 50);
    F.line = 10;
    context_536870919.lineTo(220, 80);
    F.line = 11;
    context_536870919.quadraticCurveTo(150, 100, 260, 170);
    F.line = 12;
    context_536870919.closePath();
    F.line = 13;
    context_536870919.fillStrokeShape(shape_536870920);
  framePtr = F.prev;

  
}

function newTriangle_536870933() {
    
function innerHEX60gensym10_536870947() {
      var result_536870948 = null;

      var F = {procname: "newTriangle.inner`gensym10", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/js/jsffi.nim", line: 0};
      framePtr = F;
      BeforeRet: {
        F.line = 425;
        F.filename = "jsffi.nim";
        var a_536870949 = null;
        F.line = 426;
        a_536870949 = {};
        F.line = 434;
        a_536870949.fill = "#00D2FF";
        F.line = 434;
        a_536870949.stroke = "black";
        F.line = 434;
        a_536870949.strokeWidth = 4;
        F.line = 434;
        a_536870949.sceneFunc = createTriangle_536870918;
        F.line = 445;
        result_536870948 = a_536870949;
        break BeforeRet;
      };
      framePtr = F.prev;

      return result_536870948;

    }

  var result_536870934 = null;

  var F = {procname: "ex01_shapes.newTriangle", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/examples/ex01_shapes.nim", line: 0};
  framePtr = F;
    F.line = 16;
    F.filename = "ex01_shapes.nim";
    result_536870934 = new Konva.Shape(innerHEX60gensym10_536870947());
  framePtr = F.prev;

  return result_536870934;

}

function toCdouble_536871166(val_536871168) {
  var result_536871169 = 0.0;

  var F = {procname: "toCdouble.toCdouble", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/src/common/converters.nim", line: 0};
  framePtr = F;
    F.line = 13;
    F.filename = "converters.nim";
    result_536871169 = val_536871168;
  framePtr = F.prev;

  return result_536871169;

}

function main_536871013() {
    
function innerHEX60gensym25_536871018() {
      var result_536871019 = null;

      var F = {procname: "main.inner`gensym25", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/js/jsffi.nim", line: 0};
      framePtr = F;
      BeforeRet: {
        F.line = 425;
        F.filename = "jsffi.nim";
        var a_536871020 = null;
        F.line = 426;
        a_536871020 = {};
        F.line = 434;
        a_536871020.x = HEX2F_33556020(((stage_536871014.width()) | 0), 2);
        F.line = 41;
        F.filename = "ex01_shapes.nim";
        a_536871020.y = HEX2F_33556020(((stage_536871014.height()) | 0), 2);
        F.line = 434;
        F.filename = "jsffi.nim";
        a_536871020.radius = 70.0;
        F.line = 434;
        a_536871020.fill = "red";
        F.line = 434;
        a_536871020.stroke = "black";
        F.line = 434;
        a_536871020.strokeWidth = 4;
        F.line = 445;
        result_536871019 = a_536871020;
        break BeforeRet;
      };
      framePtr = F.prev;

      return result_536871019;

    }
    
function innerHEX60gensym42_536871045() {
      var result_536871046 = null;

      var F = {procname: "main.inner`gensym42", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/js/jsffi.nim", line: 0};
      framePtr = F;
      BeforeRet: {
        F.line = 425;
        F.filename = "jsffi.nim";
        var a_536871047 = null;
        F.line = 426;
        a_536871047 = {};
        F.line = 434;
        a_536871047.x = 20.0;
        F.line = 434;
        a_536871047.y = 20.0;
        F.line = 434;
        a_536871047.width = 100.0;
        F.line = 434;
        a_536871047.height = 50.0;
        F.line = 434;
        a_536871047.fill = "green";
        F.line = 434;
        a_536871047.stroke = "black";
        F.line = 434;
        a_536871047.strokeWidth = 4.0;
        F.line = 445;
        result_536871046 = a_536871047;
        break BeforeRet;
      };
      framePtr = F.prev;

      return result_536871046;

    }
    
function innerHEX60gensym61_536871067() {
      var result_536871068 = null;

      var F = {procname: "main.inner`gensym61", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/js/jsffi.nim", line: 0};
      framePtr = F;
      BeforeRet: {
        F.line = 425;
        F.filename = "jsffi.nim";
        var a_536871069 = null;
        F.line = 426;
        a_536871069 = {};
        F.line = 434;
        a_536871069.x = 150.0;
        F.line = 434;
        a_536871069.y = 40.0;
        F.line = 434;
        a_536871069.width = 100.0;
        F.line = 434;
        a_536871069.height = 50.0;
        F.line = 434;
        a_536871069.fill = "red";
        F.line = 434;
        a_536871069.stroke = "black";
        F.line = 434;
        a_536871069.shadowBlur = 10;
        F.line = 434;
        a_536871069.cornerRadius = 10.0;
        F.line = 445;
        result_536871068 = a_536871069;
        break BeforeRet;
      };
      framePtr = F.prev;

      return result_536871068;

    }
    
function innerHEX60gensym76_536871073() {
      var result_536871074 = null;

      var F = {procname: "main.inner`gensym76", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/js/jsffi.nim", line: 0};
      framePtr = F;
      BeforeRet: {
        F.line = 425;
        F.filename = "jsffi.nim";
        var a_536871075 = null;
        F.line = 426;
        a_536871075 = {};
        F.line = 434;
        a_536871075.x = HEX2F_33556020(((stage_536871014.width()) | 0), 2);
        F.line = 434;
        a_536871075.y = 15.0;
        F.line = 434;
        a_536871075.text = "Simple Text";
        F.line = 434;
        a_536871075.fontSize = 30;
        F.line = 434;
        a_536871075.fontFamily = "Calibri";
        F.line = 436;
        a_536871075.stroke = [103,114,101,101,110];
        F.line = 445;
        result_536871074 = a_536871075;
        break BeforeRet;
      };
      framePtr = F.prev;

      return result_536871074;

    }
    
function innerHEX60gensym99_536871124() {
      var result_536871125 = null;

      var F = {procname: "main.inner`gensym99", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/js/jsffi.nim", line: 0};
      framePtr = F;
      BeforeRet: {
        F.line = 425;
        F.filename = "jsffi.nim";
        var a_536871126 = null;
        F.line = 426;
        a_536871126 = {};
        F.line = 434;
        a_536871126.x = 20.0;
        F.line = 434;
        a_536871126.y = 60.0;
        F.line = 434;
        a_536871126.text = "COMPLEX TEXT\nll the world's a stage, and all the men and women merely players. They have their exits and their entrances.";
        F.line = 434;
        a_536871126.fontSize = 18;
        F.line = 434;
        a_536871126.fontFamily = "Calibri";
        F.line = 436;
        a_536871126.stroke = [35,53,53,53];
        F.line = 436;
        a_536871126.width = 300;
        F.line = 434;
        a_536871126.padding = 20;
        F.line = 434;
        a_536871126.align = "center";
        F.line = 445;
        result_536871125 = a_536871126;
        break BeforeRet;
      };
      framePtr = F.prev;

      return result_536871125;

    }
    
function innerHEX60gensym132_536871163() {
      var result_536871164 = null;

      var F = {procname: "main.inner`gensym132", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/js/jsffi.nim", line: 0};
      framePtr = F;
      BeforeRet: {
        F.line = 425;
        F.filename = "jsffi.nim";
        var a_536871165 = null;
        F.line = 426;
        a_536871165 = {};
        F.line = 434;
        a_536871165.x = 20.0;
        F.line = 434;
        a_536871165.y = 60.0;
        F.line = 434;
        a_536871165.width = 300.0;
        F.line = 434;
        a_536871165.height = toCdouble_536871166(complexText_536871160.height());
        F.line = 434;
        a_536871165.fill = "#ddd";
        F.line = 434;
        a_536871165.stroke = "#555";
        F.line = 434;
        a_536871165.strokeWidth = 5.0;
        F.line = 434;
        a_536871165.shadowColor = "black";
        F.line = 434;
        a_536871165.shadowBlur = 10;
        F.line = 434;
        a_536871165.shadowOffsetX = 10;
        F.line = 436;
        a_536871165.shadowOffsetY = 10;
        F.line = 434;
        a_536871165.shadowOpacity = 0.2;
        F.line = 434;
        a_536871165.cornerRadius = 10.0;
        F.line = 445;
        result_536871164 = a_536871165;
        break BeforeRet;
      };
      framePtr = F.prev;

      return result_536871164;

    }
    
function innerHEX60gensym147_536871192() {
      var result_536871193 = null;

      var F = {procname: "main.inner`gensym147", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.2/lib/js/jsffi.nim", line: 0};
      framePtr = F;
      BeforeRet: {
        F.line = 425;
        F.filename = "jsffi.nim";
        var a_536871194 = null;
        F.line = 426;
        a_536871194 = {};
        F.line = 434;
        a_536871194.text = "Tooltip pointing down";
        F.line = 434;
        a_536871194.fontFamily = "Calibri";
        F.line = 434;
        a_536871194.fontSize = 18;
        F.line = 434;
        a_536871194.padding = 5;
        F.line = 434;
        a_536871194.fill = "white";
        F.line = 445;
        result_536871193 = a_536871194;
        break BeforeRet;
      };
      framePtr = F.prev;

      return result_536871193;

    }
    
function HEX3Aanonymous_536871199(evt_536871200) {
      var F = {procname: "main.:anonymous", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/examples/ex01_shapes.nim", line: 0};
      framePtr = F;
        F.line = 99;
        F.filename = "ex01_shapes.nim";
        console.log("Mouseover circle");
      framePtr = F.prev;

      
    }

  var F = {procname: "ex01_shapes.main", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/examples/ex01_shapes.nim", line: 0};
  framePtr = F;
    F.line = 39;
    F.filename = "ex01_shapes.nim";
    var stage_536871014 = newStage_1107296270([99,111,110,116,97,105,110,101,114], 1000, 800);
    F.line = 40;
    var layer_536871015 = new Konva.Layer();
    F.line = 41;
    var circle_536871041 = new Konva.Circle(innerHEX60gensym25_536871018());
    F.line = 43;
    var triangle_536871042 = newTriangle_536870933();
    F.line = 44;
    var rect1_536871064 = new Konva.Rect(innerHEX60gensym42_536871045());
    F.line = 46;
    var rect2_536871070 = new Konva.Rect(innerHEX60gensym61_536871067());
    F.line = 50;
    layer_536871015.add(rect1_536871064);
    F.line = 51;
    layer_536871015.add(rect2_536871070);
    F.line = 54;
    var simpleText_536871121 = new Konva.Text(innerHEX60gensym76_536871073());
    F.line = 58;
    simpleText_536871121.offsetX(((HEX2F_33556020(((simpleText_536871121.width()) | 0), 2)) | 0));
    F.line = 59;
    layer_536871015.add(simpleText_536871121);
    F.line = 64;
    var complexText_536871160 = new Konva.Text(innerHEX60gensym99_536871124());
    F.line = 70;
    var rect_536871187 = new Konva.Rect(innerHEX60gensym132_536871163());
    F.line = 75;
    layer_536871015.add(rect_536871187);
    F.line = 76;
    layer_536871015.add(complexText_536871160);
    F.line = 79;
    var tooltip_536871188 = new Konva.Label({x: 300, y: 200, opacity: 0.75, m_type: NTI1040187401});
    F.line = 80;
    var tag_536871189 = new Konva.Tag({fill: "black", pointerDirection: "down", pointerWidth: 10, pointerHeight: 10, lineJoin: "round", shadowColor: "black", shadowBlur: 10, shadowOffsetX: 10, shadowOffsetY: 10, shadowOpacity: 0.5, m_type: NTI1056964614});
    F.line = 90;
    var tooltipText_536871198 = new Konva.Text(innerHEX60gensym147_536871192());
    F.line = 98;
    circle_536871041.on("mouseover", HEX3Aanonymous_536871199);
    F.line = 102;
    tooltip_536871188.add(tag_536871189);
    F.line = 103;
    tooltip_536871188.add(tooltipText_536871198);
    F.line = 104;
    layer_536871015.add(tooltip_536871188);
    F.line = 105;
    layer_536871015.add(triangle_536871042);
    F.line = 106;
    layer_536871015.add(circle_536871041);
    F.line = 107;
    stage_536871014.add(layer_536871015);
    F.line = 108;
    layer_536871015.draw();
  framePtr = F.prev;

  
}
var F = {procname: "module ex01_shapes", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/examples/ex01_shapes.nim", line: 0};
framePtr = F;
F.line = 110;
F.filename = "ex01_shapes.nim";
main_536871013();
framePtr = F.prev;
var F = {procname: "module ex01_shapes", prev: framePtr, filename: "/home/jose/src/nimlang/konva.nim/examples/ex01_shapes.nim", line: 0};
framePtr = F;
framePtr = F.prev;
