/* Generated by the Nim Compiler v2.0.14 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI1140850695 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI1140850694 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1040187398 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI536870936 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI536870923 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33554466 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI1006632967 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI536870921 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI536870920 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI704643078 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI704643077 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1023410180 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1006632966 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI1006632965 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1006632963 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI1358954590 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI1056964614 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1124073482 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI1124073481 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555183 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI721420368 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI184549387 = {size: 0,kind: 34,base: null,node: null,finalizer: null};
var NTI184549391 = {size: 0,kind: 36,base: null,node: null,finalizer: null};
var NTI1073741831 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI33555838 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555173 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555181 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555180 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555177 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555178 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
var NNI33555178 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555178.node = NNI33555178;
NTI33555180.base = NTI33555177;
NTI33555181.base = NTI33555177;
var NNI33555177 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555180, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555181, name: "up", sons: null}]};
NTI33555177.node = NNI33555177;
var NNI33555173 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555173.node = NNI33555173;
NTI33555177.base = NTI33555173;
NTI33555178.base = NTI33555177;
NTI134217741.base = NTI33555178;
NTI134217743.base = NTI134217741;
var NNI33555838 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554450, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554450, name: "Field2", sons: null}]};
NTI33555838.node = NNI33555838;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555178;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555178;
var NNI1073741831 = {kind: 2, len: 10, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "x", len: 0, typ: NTI184549391, name: "x", sons: null}, 
{kind: 1, offset: "y", len: 0, typ: NTI184549391, name: "y", sons: null}, 
{kind: 1, offset: "text", len: 0, typ: NTI33554450, name: "text", sons: null}, 
{kind: 1, offset: "fontFamily", len: 0, typ: NTI33554450, name: "fontFamily", sons: null}, 
{kind: 1, offset: "fontSize", len: 0, typ: NTI184549387, name: "fontSize", sons: null}, 
{kind: 1, offset: "padding", len: 0, typ: NTI184549387, name: "padding", sons: null}, 
{kind: 1, offset: "fill", len: 0, typ: NTI33554450, name: "fill", sons: null}, 
{kind: 1, offset: "align", len: 0, typ: NTI33554450, name: "align", sons: null}, 
{kind: 1, offset: "stroke", len: 0, typ: NTI33554450, name: "stroke", sons: null}, 
{kind: 1, offset: "width", len: 0, typ: NTI184549387, name: "width", sons: null}]};
NTI1073741831.node = NNI1073741831;
var NNI721420368 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI721420368.node = NNI721420368;
var NNI33555183 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555183.node = NNI33555183;
NTI33555183.base = NTI33555173;
NTI721420368.base = NTI33555183;
NTI1073741831.base = NTI721420368;
NTI1124073482.base = NTI33554435;
var NNI1124073481 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "points", len: 0, typ: NTI1124073482, name: "points", sons: null}, 
{kind: 1, offset: "stroke", len: 0, typ: NTI33554450, name: "stroke", sons: null}, 
{kind: 1, offset: "strokeWidth", len: 0, typ: NTI184549387, name: "strokeWidth", sons: null}, 
{kind: 1, offset: "lineCap", len: 0, typ: NTI33554450, name: "lineCap", sons: null}, 
{kind: 1, offset: "lineJoin", len: 0, typ: NTI33554450, name: "lineJoin", sons: null}]};
NTI1124073481.node = NNI1124073481;
NTI1124073481.base = NTI721420368;
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
NTI134217745.base = NTI33555178;
var NNI1056964614 = {kind: 2, len: 13, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "x", len: 0, typ: NTI184549391, name: "x", sons: null}, 
{kind: 1, offset: "y", len: 0, typ: NTI184549391, name: "y", sons: null}, 
{kind: 1, offset: "width", len: 0, typ: NTI184549391, name: "width", sons: null}, 
{kind: 1, offset: "height", len: 0, typ: NTI184549391, name: "height", sons: null}, 
{kind: 1, offset: "fill", len: 0, typ: NTI33554450, name: "fill", sons: null}, 
{kind: 1, offset: "stroke", len: 0, typ: NTI33554450, name: "stroke", sons: null}, 
{kind: 1, offset: "strokeWidth", len: 0, typ: NTI184549391, name: "strokeWidth", sons: null}, 
{kind: 1, offset: "cornerRadius", len: 0, typ: NTI184549391, name: "cornerRadius", sons: null}, 
{kind: 1, offset: "shadowColor", len: 0, typ: NTI33554450, name: "shadowColor", sons: null}, 
{kind: 1, offset: "shadowBlur", len: 0, typ: NTI184549387, name: "shadowBlur", sons: null}, 
{kind: 1, offset: "shadowOffsetX", len: 0, typ: NTI184549387, name: "shadowOffsetX", sons: null}, 
{kind: 1, offset: "shadowOffsetY", len: 0, typ: NTI184549387, name: "shadowOffsetY", sons: null}, 
{kind: 1, offset: "shadowOpacity", len: 0, typ: NTI184549391, name: "shadowOpacity", sons: null}]};
NTI1056964614.node = NNI1056964614;
NTI1056964614.base = NTI721420368;
var NNI1006632965 = {kind: 1, offset: "add", len: 0, typ: NTI1006632966, name: "add", sons: null};
NTI1006632965.node = NNI1006632965;
var NNI1023410180 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI1023410180.node = NNI1023410180;
var NNI704643077 = {kind: 1, offset: "on", len: 0, typ: NTI704643078, name: "on", sons: null};
NTI704643077.node = NNI704643077;
NTI704643077.base = NTI721420368;
NTI1023410180.base = NTI704643077;
NTI1006632965.base = NTI1023410180;
NTI1006632963.base = NTI1006632965;
NTI1358954590.base = NTI1006632963;
NTI536870921.base = NTI33554449;
var NNI536870920 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "n", len: 0, typ: NTI33554435, name: "n", sons: null}, 
{kind: 1, offset: "title", len: 0, typ: NTI33554449, name: "title", sons: null}, 
{kind: 1, offset: "by", len: 0, typ: NTI536870921, name: "by", sons: null}]};
NTI536870920.node = NNI536870920;
var NNI1006632967 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "x", len: 0, typ: NTI184549391, name: "x", sons: null}, 
{kind: 1, offset: "y", len: 0, typ: NTI184549391, name: "y", sons: null}, 
{kind: 1, offset: "width", len: 0, typ: NTI184549391, name: "width", sons: null}, 
{kind: 1, offset: "height", len: 0, typ: NTI184549391, name: "height", sons: null}, 
{kind: 1, offset: "draggable", len: 0, typ: NTI33554466, name: "draggable", sons: null}]};
NTI1006632967.node = NNI1006632967;
NTI1006632967.base = NTI721420368;
NTI536870920.base = NTI1006632967;
var NNI536870923 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554435, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}]};
NTI536870923.node = NNI536870923;
var NNI536870936 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554435, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}]};
NTI536870936.node = NNI536870936;
var NNI1040187398 = {kind: 2, len: 6, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "x", len: 0, typ: NTI184549391, name: "x", sons: null}, 
{kind: 1, offset: "y", len: 0, typ: NTI184549391, name: "y", sons: null}, 
{kind: 1, offset: "radius", len: 0, typ: NTI184549391, name: "radius", sons: null}, 
{kind: 1, offset: "fill", len: 0, typ: NTI33554450, name: "fill", sons: null}, 
{kind: 1, offset: "stroke", len: 0, typ: NTI33554450, name: "stroke", sons: null}, 
{kind: 1, offset: "strokeWidth", len: 0, typ: NTI184549387, name: "strokeWidth", sons: null}]};
NTI1040187398.node = NNI1040187398;
NTI1040187398.base = NTI721420368;
NTI1140850695.base = NTI184549387;
var NNI1140850694 = {kind: 2, len: 9, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "points", len: 0, typ: NTI1140850695, name: "points", sons: null}, 
{kind: 1, offset: "tension", len: 0, typ: NTI184549387, name: "tension", sons: null}, 
{kind: 1, offset: "pointerLength", len: 0, typ: NTI184549387, name: "pointerLength", sons: null}, 
{kind: 1, offset: "pointerWidth", len: 0, typ: NTI184549387, name: "pointerWidth", sons: null}, 
{kind: 1, offset: "pointerAtBeginning", len: 0, typ: NTI33554466, name: "pointerAtBeginning", sons: null}, 
{kind: 1, offset: "pointerAtEnding", len: 0, typ: NTI33554466, name: "pointerAtEnding", sons: null}, 
{kind: 1, offset: "fill", len: 0, typ: NTI33554450, name: "fill", sons: null}, 
{kind: 1, offset: "stroke", len: 0, typ: NTI33554450, name: "stroke", sons: null}, 
{kind: 1, offset: "strokeWidth", len: 0, typ: NTI184549387, name: "strokeWidth", sons: null}]};
NTI1140850694.node = NNI1140850694;
NTI1140850694.base = NTI721420368;

function mnewString(len_33557003) {
        var result = new Array(len_33557003);
    for (var i = 0; i < len_33557003; i++) {result[i] = 0;}
    return result;
  

  
}

function arrayConstr(len_33557314, value_33557315, typ_33557316) {
        var result = new Array(len_33557314);
    for (var i = 0; i < len_33557314; ++i) result[i] = nimCopy(null, value_33557315, typ_33557316);
    return result;
  

  
}

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_33557268, src_33557269, ti_33557270) {
  var result_33557279 = null;

    switch (ti_33557270.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_33557259(ti_33557270))) {
      result_33557279 = src_33557269;
      }
      else {
        result_33557279 = [src_33557269[0], src_33557269[1]];
      }
      
      break;
    case 19:
            if (dest_33557268 === null || dest_33557268 === undefined) {
        dest_33557268 = {};
      }
      else {
        for (var key in dest_33557268) { delete dest_33557268[key]; }
      }
      for (var key in src_33557269) { dest_33557268[key] = src_33557269[key]; }
      result_33557279 = dest_33557268;
    
      break;
    case 18:
    case 17:
      if (!((ti_33557270.base == null))) {
      result_33557279 = nimCopy(dest_33557268, src_33557269, ti_33557270.base);
      }
      else {
      if ((ti_33557270.kind == 17)) {
      result_33557279 = (dest_33557268 === null || dest_33557268 === undefined) ? {m_type: ti_33557270} : dest_33557268;
      }
      else {
        result_33557279 = (dest_33557268 === null || dest_33557268 === undefined) ? {} : dest_33557268;
      }
      }
      nimCopyAux(result_33557279, src_33557269, ti_33557270.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_33557269)) { 
        if(dest_33557268 === null || dest_33557268 === undefined || dest_33557268.length != src_33557269.length) {
          dest_33557268 = new src_33557269.constructor(src_33557269);
        } else {
          dest_33557268.set(src_33557269, 0);
        }
        result_33557279 = dest_33557268;
      } else {
        if (src_33557269 === null) {
          result_33557279 = null;
        }
        else {
          if (dest_33557268 === null || dest_33557268 === undefined || dest_33557268.length != src_33557269.length) {
            dest_33557268 = new Array(src_33557269.length);
          }
          result_33557279 = dest_33557268;
          for (var i = 0; i < src_33557269.length; ++i) {
            result_33557279[i] = nimCopy(result_33557279[i], src_33557269[i], ti_33557270.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_33557269 === null) {
        result_33557279 = null;
      }
      else {
        if (dest_33557268 === null || dest_33557268 === undefined || dest_33557268.length != src_33557269.length) {
          dest_33557268 = new Array(src_33557269.length);
        }
        result_33557279 = dest_33557268;
        for (var i = 0; i < src_33557269.length; ++i) {
          result_33557279[i] = nimCopy(result_33557279[i], src_33557269[i], ti_33557270.base);
        }
      }
    
      break;
    case 28:
            if (src_33557269 !== null) {
        result_33557279 = src_33557269.slice(0);
      }
    
      break;
    default: 
      result_33557279 = src_33557269;
      break;
    }

  return result_33557279;

}

function cstrToNimstr(c_33556898) {
      var ln = c_33556898.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_33556898.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_33556898.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function toJSStr(s_33556901) {
  var result_33556902 = null;

    var res_33556943 = newSeq_33556919((s_33556901).length);
    var i_33556944 = 0;
    var j_33556945 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556944 < (s_33556901).length)) break Label2;
          var c_33556946 = s_33556901[i_33556944];
          if ((c_33556946 < 128)) {
          res_33556943[j_33556945] = String.fromCharCode(c_33556946);
          i_33556944 += 1;
          }
          else {
            var helper_33556959 = newSeq_33556919(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556960 = c_33556946.toString(16);
                  if ((((code_33556960) == null ? 0 : (code_33556960).length) == 1)) {
                  helper_33556959.push("%0");;
                  }
                  else {
                  helper_33556959.push("%");;
                  }
                  
                  helper_33556959.push(code_33556960);;
                  i_33556944 += 1;
                  if ((((s_33556901).length <= i_33556944) || (s_33556901[i_33556944] < 128))) {
                  break Label3;
                  }
                  
                  c_33556946 = s_33556901[i_33556944];
                }
            };
++excHandler;
            try {
            res_33556943[j_33556945] = decodeURIComponent(helper_33556959.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556943[j_33556945] = helper_33556959.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556945 += 1;
        }
    };
    if (res_33556943.length < j_33556945) { for (var i = res_33556943.length ; i < j_33556945 ; ++i) res_33556943.push(null); }
               else { res_33556943.length = j_33556945; };
    result_33556902 = res_33556943.join("");

  return result_33556902;

}

function raiseException(e_33556653, ename_33556654) {
    e_33556653.name = ename_33556654;
    if ((excHandler == 0)) {
    unhandledException(e_33556653);
    }
    
    e_33556653.trace = nimCopy(null, rawWriteStackTrace_33556604(), NTI33554449);
    throw e_33556653;

  
}

function addInt(a_33557050, b_33557051) {
        var result = a_33557050 + b_33557051;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_33557324, a_33557325, b_33557326) {
  var result_33557327 = 0;

  BeforeRet: {
    if (((a_33557325 <= i_33557324) && (i_33557324 <= b_33557326))) {
    result_33557327 = i_33557324;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557327;

}

function chckIndx(i_33557319, a_33557320, b_33557321) {
  var result_33557322 = 0;

  BeforeRet: {
    if (((a_33557320 <= i_33557319) && (i_33557319 <= b_33557321))) {
    result_33557322 = i_33557319;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_33557319, a_33557320, b_33557321);
    }
    
  };

  return result_33557322;

}

function negInt(a_33557092) {
  var result_33557093 = 0;

    result_33557093 = (a_33557092 * (-1));

  return result_33557093;

}

function makeNimstrLit(c_33556895) {
      var result = [];
  for (var i = 0; i < c_33556895.length; ++i) {
    result[i] = c_33556895.charCodeAt(i);
  }
  return result;
  

  
}

function subInt(a_33557054, b_33557055) {
        var result = a_33557054 - b_33557055;
    checkOverflowInt(result);
    return result;
  

  
}
var F = {procname: "module macros", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module hashes", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/hashes.nim", line: 0};
framePtr = F;
F.line = 218;
F.filename = "hashes.nim";
var objectID_771752113 = [0];
framePtr = F.prev;
var F = {procname: "module hashes", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/hashes.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module outparams", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/std/outparams.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module outparams", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/std/outparams.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/collections/tables.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/collections/tables.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsffi", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/js/jsffi.nim", line: 0};
framePtr = F;
F.line = 45;
F.filename = "jsffi.nim";
F.line = 46;
framePtr = F.prev;
var F = {procname: "module jsffi", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/js/jsffi.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module dom", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/js/dom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module dom", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/js/dom.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module types", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/types.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module types", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/types.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module shape", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/shape.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module shape", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/shape.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module container", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/container.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module container", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/container.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module group", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/group.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module group", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/group.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module circle", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/circle.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module circle", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/circle.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module rect", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/rect.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module rect", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/rect.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module text", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/text.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module text", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/text.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tag", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/tag.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tag", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/tag.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module label", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/label.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module label", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/label.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module line", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/line.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module line", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/line.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module arrow", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/arrow.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module arrow", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/arrow.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module node", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/node.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module node", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/node.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module regularpolygon", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/regularpolygon.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module regularpolygon", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/shapes/regularpolygon.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module layer", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/layer/layer.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module layer", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/layer/layer.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module stage", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/stage/stage.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module stage", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/stage/stage.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module konva", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/common/konva.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module konva", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/common/konva.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module converters", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/common/converters.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module converters", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/common/converters.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module filters", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/filters/filters.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module konva", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module konva", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tkonva", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/diagram/tkonva.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tkonva", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/diagram/tkonva.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module box", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/diagram/box.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module box", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/diagram/box.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module diagram", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/diagram/diagram.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module diagram", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/diagram/diagram.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsconsole", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/js/jsconsole.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module link", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/diagram/link.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module link", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/diagram/link.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strformat", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/strformat.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strformat", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/strformat.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module step", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/diagram/step.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module step", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/diagram/step.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module diagram", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/diagram.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module diagram", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/diagram.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function add_33556373(x_33556374, x_33556374_Idx, y_33556375) {
          if (x_33556374[x_33556374_Idx] === null) { x_33556374[x_33556374_Idx] = []; }
      var off = x_33556374[x_33556374_Idx].length;
      x_33556374[x_33556374_Idx].length += y_33556375.length;
      for (var i = 0; i < y_33556375.length; ++i) {
        x_33556374[x_33556374_Idx][off+i] = y_33556375.charCodeAt(i);
      }
    

  
}

function isFatPointer_33557259(ti_33557260) {
  var result_33557261 = false;

  BeforeRet: {
    result_33557261 = !((ConstSet1[ti_33557260.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557261;

}

function nimCopyAux(dest_33557272, src_33557273, n_33557274) {
    switch (n_33557274.kind) {
    case 0:
      break;
    case 1:
            dest_33557272[n_33557274.offset] = nimCopy(dest_33557272[n_33557274.offset], src_33557273[n_33557274.offset], n_33557274.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_33557274.sons.length; i++) {
      nimCopyAux(dest_33557272, src_33557273, n_33557274.sons[i]);
    }
    
      break;
    case 3:
            dest_33557272[n_33557274.offset] = nimCopy(dest_33557272[n_33557274.offset], src_33557273[n_33557274.offset], n_33557274.typ);
      for (var i = 0; i < n_33557274.sons.length; ++i) {
        nimCopyAux(dest_33557272, src_33557273, n_33557274.sons[i][1]);
      }
    
      break;
    }

  
}

function auxWriteStackTrace_33556508(f_33556509) {
  var result_33556510 = [[]];

    var it_33556518 = f_33556509;
    var i_33556519 = 0;
    var total_33556520 = 0;
    var tempFrames_33556521 = arrayConstr(64, {Field0: null, Field1: 0, Field2: null}, NTI33555838);
    Label1: {
        Label2: while (true) {
        if (!(!((it_33556518 == null)) && (i_33556519 <= 63))) break Label2;
          tempFrames_33556521[i_33556519].Field0 = it_33556518.procname;
          tempFrames_33556521[i_33556519].Field1 = it_33556518.line;
          tempFrames_33556521[i_33556519].Field2 = it_33556518.filename;
          i_33556519 += 1;
          total_33556520 += 1;
          it_33556518 = it_33556518.prev;
        }
    };
    Label3: {
        Label4: while (true) {
        if (!!((it_33556518 == null))) break Label4;
          total_33556520 += 1;
          it_33556518 = it_33556518.prev;
        }
    };
    result_33556510[0] = nimCopy(null, [], NTI33554449);
    if (!((total_33556520 == i_33556519))) {
    result_33556510[0].push.apply(result_33556510[0], [40]);;
    result_33556510[0].push.apply(result_33556510[0], HEX24_369098760((total_33556520 - i_33556519)));;
    result_33556510[0].push.apply(result_33556510[0], [32,99,97,108,108,115,32,111,109,105,116,116,101,100,41,32,46,46,46,10]);;
    }
    
    Label5: {
      var j_33556554 = 0;
      var colontmp__536871432 = 0;
      colontmp__536871432 = (i_33556519 - 1);
      var res_536871434 = colontmp__536871432;
      Label6: {
          Label7: while (true) {
          if (!(0 <= res_536871434)) break Label7;
            j_33556554 = res_536871434;
            result_33556510[0].push.apply(result_33556510[0], cstrToNimstr(tempFrames_33556521[j_33556554].Field2));;
            if ((0 < tempFrames_33556521[j_33556554].Field1)) {
            result_33556510[0].push.apply(result_33556510[0], [40]);;
            addInt_301990129(result_33556510, 0, tempFrames_33556521[j_33556554].Field1);
            if (false) {
            result_33556510[0].push.apply(result_33556510[0], [44,32]);;
            addInt_301990129(result_33556510, 0, 0);
            }
            
            result_33556510[0].push.apply(result_33556510[0], [41]);;
            }
            
            result_33556510[0].push.apply(result_33556510[0], [32,97,116,32]);;
            add_33556373(result_33556510, 0, tempFrames_33556521[j_33556554].Field0);
            result_33556510[0].push.apply(result_33556510[0], [10]);;
            res_536871434 -= 1;
          }
      };
    };

  return result_33556510[0];

}

function rawWriteStackTrace_33556604() {
  var result_33556605 = [];

    if (!((framePtr == null))) {
    result_33556605 = nimCopy(null, ([84,114,97,99,101,98,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,108,97,115,116,41,10] || []).concat(auxWriteStackTrace_33556508(framePtr) || []), NTI33554449);
    }
    else {
      result_33556605 = nimCopy(null, [78,111,32,115,116,97,99,107,32,116,114,97,99,101,98,97,99,107,32,97,118,97,105,108,97,98,108,101,10], NTI33554449);
    }
    

  return result_33556605;

}

function newSeq_33556919(len_33556921) {
  var result_33556922 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 638;
    F.filename = "system.nim";
    result_33556922 = new Array(len_33556921); for (var i = 0 ; i < len_33556921 ; ++i) { result_33556922[i] = null; }  framePtr = F.prev;

  return result_33556922;

}

function unhandledException(e_33556649) {
    var buf_33556650 = [[]];
    if (!(((e_33556649.message).length == 0))) {
    buf_33556650[0].push.apply(buf_33556650[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556650[0].push.apply(buf_33556650[0], e_33556649.message);;
    }
    else {
    buf_33556650[0].push.apply(buf_33556650[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556650[0].push.apply(buf_33556650[0], [32,91]);;
    add_33556373(buf_33556650, 0, e_33556649.name);
    buf_33556650[0].push.apply(buf_33556650[0], [93,10]);;
    buf_33556650[0].push.apply(buf_33556650[0], rawWriteStackTrace_33556604());;
    var cbuf_33556651 = toJSStr(buf_33556650[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556651);
  }
  else {
    throw cbuf_33556651;
  }
  

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_33557048) {
        if (a_33557048 > 2147483647 || a_33557048 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function raiseIndexError(i_33556812, a_33556813, b_33556814) {
    var Temporary1;

    if ((b_33556814 < a_33556813)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32] || []).concat(HEX24_369098760(i_33556812) || [],[32,110,111,116,32,105,110,32] || [],HEX24_369098760(a_33556813) || [],[32,46,46,32] || [],HEX24_369098760(b_33556814) || []);
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function addChars_301990090(result_301990092, result_301990092_Idx, x_301990093, start_301990094, n_301990095) {
    var Temporary1;

  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 43;
    F.filename = "digitsutils.nim";
    var old_301990096 = (result_301990092[result_301990092_Idx]).length;
    F.line = 44;
    if (result_301990092[result_301990092_Idx].length < (Temporary1 = chckRange(addInt(old_301990096, n_301990095), 0, 2147483647), Temporary1)) { for (var i = result_301990092[result_301990092_Idx].length; i < Temporary1; ++i) result_301990092[result_301990092_Idx].push(0); }
         else {result_301990092[result_301990092_Idx].length = Temporary1; };
    Label2: {
      F.line = 46;
      var iHEX60gensym4_301990110 = 0;
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_536871427 = 0;
      Label3: {
        F.line = 129;
          Label4: while (true) {
          if (!(i_536871427 < n_301990095)) break Label4;
            F.line = 49;
            F.filename = "digitsutils.nim";
            iHEX60gensym4_301990110 = i_536871427;
            F.line = 46;
            result_301990092[result_301990092_Idx][chckIndx(addInt(old_301990096, iHEX60gensym4_301990110), 0, (result_301990092[result_301990092_Idx]).length - 1)] = x_301990093.charCodeAt(chckIndx(addInt(start_301990094, iHEX60gensym4_301990110), 0, (x_301990093).length - 1));
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_536871427 = addInt(i_536871427, 1);
          }
      };
    };
  framePtr = F.prev;

  
}

function addChars_301990086(result_301990088, result_301990088_Idx, x_301990089) {
  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 55;
    F.filename = "digitsutils.nim";
    addChars_301990090(result_301990088, result_301990088_Idx, x_301990089, 0, ((x_301990089) == null ? 0 : (x_301990089).length));
  framePtr = F.prev;

  
}

function addInt_301990111(result_301990112, result_301990112_Idx, x_301990113) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 111;
    F.filename = "digitsutils.nim";
    addChars_301990086(result_301990112, result_301990112_Idx, ((x_301990113) + ""));
  framePtr = F.prev;

  
}

function addInt_301990129(result_301990130, result_301990130_Idx, x_301990131) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 115;
    F.filename = "digitsutils.nim";
    addInt_301990111(result_301990130, result_301990130_Idx, BigInt(x_301990131));
  framePtr = F.prev;

  
}

function HEX24_369098760(x_369098761) {
  var result_369098762 = [[]];

  var F = {procname: "dollars.$", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/system/dollars.nim", line: 0};
  framePtr = F;
    F.line = 18;
    F.filename = "dollars.nim";
    addInt_301990129(result_369098762, 0, x_369098761);
  framePtr = F.prev;

  return result_369098762[0];

}

function formatValue_1358954526(result_1358954529, result_1358954529_Idx, value_1358954530) {
  var F = {procname: "formatValue.formatValue", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/pure/strformat.nim", line: 0};
  framePtr = F;
    F.line = 492;
    F.filename = "strformat.nim";
    result_1358954529[result_1358954529_Idx].push.apply(result_1358954529[result_1358954529_Idx], HEX24_369098760(value_1358954530));;
  framePtr = F.prev;

  
}

function sysFatal_268435501(message_268435504) {
  var F = {procname: "sysFatal.sysFatal", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/system/fatal.nim", line: 0};
  framePtr = F;
    F.line = 53;
    F.filename = "fatal.nim";
    raiseException({message: nimCopy(null, message_268435504, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");
  framePtr = F.prev;

  
}

function raiseAssert_268435499(msg_268435500) {
  var F = {procname: "assertions.raiseAssert", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 36;
    F.filename = "assertions.nim";
    sysFatal_268435501(msg_268435500);
  framePtr = F.prev;

  
}

function failedAssertImpl_268435541(msg_268435542) {
  var F = {procname: "assertions.failedAssertImpl", prev: framePtr, filename: "/home/jose/.choosenim/toolchains/nim-2.0.14/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 41;
    F.filename = "assertions.nim";
    raiseAssert_268435499(msg_268435542);
  framePtr = F.prev;

  
}

function toCdouble_536870998(val_536871000) {
  var result_536871001 = 0.0;

  var F = {procname: "toCdouble.toCdouble", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/common/converters.nim", line: 0};
  framePtr = F;
    F.line = 13;
    F.filename = "converters.nim";
    result_536871001 = val_536871000;
  framePtr = F.prev;

  return result_536871001;

}

function toCdouble_1325400075(val_1325400077) {
  var result_1325400078 = 0.0;

  var F = {procname: "toCdouble.toCdouble", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/src/konva/common/converters.nim", line: 0};
  framePtr = F;
    F.line = 13;
    F.filename = "converters.nim";
    result_1325400078 = val_1325400077;
  framePtr = F.prev;

  return result_1325400078;

}

function newStep_536870961(val_536870962) {
  var result_536870963 = null;

  var F = {procname: "ex03_editable.newStep", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/examples/ex03_editable.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 47;
    F.filename = "ex03_editable.nim";
    var newVal_536870964 = val_536870962;
    if (!((0.0 < val_536870962.width))) {
    F.line = 49;
    newVal_536870964.width = 200.0;
    }
    
    if (!(val_536870962.draggable)) {
    F.line = 51;
    newVal_536870964.draggable = true;
    }
    
    F.line = 52;
    var headerHeight_536870965 = 50;
    F.line = 53;
    var titleHeight_536870966 = 100;
    F.line = 57;
    var group_536870967 = new Konva.Group(newVal_536870964);
    F.line = 60;
    var stepNumberH_536870968 = 20;
    F.line = 61;
    Label1: {
      F.line = 62;
      var fmtRes_536870972 = [mnewString(0)];
      F.line = 62;
      formatValue_1358954526(fmtRes_536870972, 0, val_536870962.n);
    };
    var stepNumber_536870979 = new Konva.Text({width: ((group_536870967.width()) | 0), text: toJSStr(fmtRes_536870972[0]), fontSize: 25, fontFamily: "Calibri", fill: "darkgray", align: "left", padding: 10, m_type: NTI1073741831, x: 0.0, y: 0.0, stroke: null});
    F.line = 66;
    group_536870967.add(stepNumber_536870979);
    F.line = 69;
    var stepTitle_536870980 = new Konva.Text({width: ((group_536870967.width()) | 0), text: toJSStr(val_536870962.title), fontSize: ((stepNumberH_536870968) | 0), fontFamily: "Arial", fill: "black", align: "center", padding: 10, m_type: NTI1073741831, x: 0.0, y: 0.0, stroke: null});
    F.line = 73;
    stepTitle_536870980.offsetY(((negInt(headerHeight_536870965)) | 0));
    F.line = 77;
    group_536870967.add(stepTitle_536870980);
    F.line = 80;
    var actioneeH_536870981 = 50;
    F.line = 81;
    var n_536870982 = 0;
    F.line = 82;
    var h_536870983 = addInt(headerHeight_536870965, titleHeight_536870966);
    Label2: {
      F.line = 83;
      var actionee_536870987 = [];
      F.line = 249;
      F.filename = "iterators.nim";
      var i_536871420 = 0;
      F.line = 250;
      var L_536871421 = (val_536870962.by).length;
      Label3: {
        F.line = 251;
          Label4: while (true) {
          if (!(i_536871420 < L_536871421)) break Label4;
            F.line = 83;
            F.filename = "ex03_editable.nim";
            actionee_536870987 = val_536870962.by[chckIndx(i_536871420, 0, (val_536870962.by).length - 1)];
            F.line = 84;
            var line_536870992 = new Konva.Line({points: [0, h_536870983, ((group_536870967.width()) | 0), h_536870983], stroke: "black", strokeWidth: 1, m_type: NTI1124073481, lineCap: null, lineJoin: null});
            F.line = 86;
            var actioneeTxt_536870993 = new Konva.Text({width: ((group_536870967.width()) | 0), text: toJSStr(actionee_536870987), fontSize: 20, fontFamily: "Arial", fill: "blue", align: "left", padding: 10, m_type: NTI1073741831, x: 0.0, y: 0.0, stroke: null});
            F.line = 89;
            actioneeTxt_536870993.offsetY(((negInt(h_536870983)) | 0));
            F.line = 90;
            h_536870983 = addInt(h_536870983, ((actioneeTxt_536870993.height()) | 0));
            F.line = 94;
            group_536870967.add(line_536870992);
            F.line = 95;
            group_536870967.add(actioneeTxt_536870993);
            F.line = 96;
            n_536870982 = addInt(n_536870982, 1);
            F.line = 13;
            F.filename = "iterators.nim";
            i_536871420 += 1;
            if (!(((val_536870962.by).length == L_536871421))) {
            F.line = 254;
            failedAssertImpl_268435541(makeNimstrLit("/home/jose/.choosenim/toolchains/nim-2.0.14/lib/system/iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    if (!((val_536870962.height == 0.0))) {
    F.line = 100;
    F.filename = "ex03_editable.nim";
    h_536870983 = ((val_536870962.height) | 0);
    }
    
    F.line = 101;
    var rect_536871002 = new Konva.Rect({width: toCdouble_536870998(((group_536870967.width()) | 0)), height: h_536870983, fill: "lightgray", stroke: "black", strokeWidth: 4.0, shadowBlur: 10, cornerRadius: 10.0, m_type: NTI1056964614, x: 0.0, y: 0.0, shadowColor: null, shadowOffsetX: 0, shadowOffsetY: 0, shadowOpacity: 0.0});
    F.line = 104;
    group_536870967.height(toCdouble_1325400075(h_536870983));
    F.line = 105;
    group_536870967.add(rect_536871002);
    F.line = 106;
    rect_536871002.zIndex(0);
    F.line = 108;
    var tmp_536871006 = group_536870967;
    F.line = 109;
    tmp_536871006.ins = nimCopy(null, [], NTI1358954590);
    F.line = 110;
    tmp_536871006.outs = nimCopy(null, [], NTI1358954590);
    F.line = 112;
    result_536870963 = tmp_536871006;
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_536870963;

}

function getRightAnchor_536870927(step_536870928) {
  var result_536870931 = {Field0: 0, Field1: 0};

  var F = {procname: "ex03_editable.getRightAnchor", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/examples/ex03_editable.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 31;
    F.filename = "ex03_editable.nim";
    var w_536870932 = step_536870928.width();
    F.line = 32;
    var h_536870933 = step_536870928.height();
    F.line = 33;
    h_536870933 = 150.0;
    F.line = 34;
    var x_536870934 = step_536870928.x();
    F.line = 35;
    var y_536870935 = step_536870928.y();
    F.line = 36;
    var colontmp__536871438 = (((x_536870934 + w_536870932)) | 0);
    F.line = 36;
    var colontmp__536871439 = (((y_536870935 + (h_536870933 / 2.0))) | 0);
    F.line = 36;
    result_536870931 = nimCopy(result_536870931, {Field0: colontmp__536871438, Field1: colontmp__536871439}, NTI536870923);
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_536870931;

}

function getLeftAnchor_536870952(step_536870953) {
  var result_536870956 = {Field0: 0, Field1: 0};

  var F = {procname: "ex03_editable.getLeftAnchor", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/examples/ex03_editable.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 39;
    F.filename = "ex03_editable.nim";
    var w_536870957 = step_536870953.width();
    F.line = 40;
    var h_536870958 = step_536870953.height();
    F.line = 41;
    h_536870958 = 150.0;
    F.line = 42;
    var x_536870959 = step_536870953.x();
    F.line = 43;
    var y_536870960 = step_536870953.y();
    F.line = 44;
    var colontmp__536871440 = ((x_536870959) | 0);
    F.line = 44;
    var colontmp__536871441 = (((y_536870960 + (h_536870958 / 2.0))) | 0);
    F.line = 44;
    result_536870956 = nimCopy(result_536870956, {Field0: colontmp__536871440, Field1: colontmp__536871441}, NTI536870936);
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_536870956;

}

function connect_536871087(step1_536871088, step2_536871089) {
  var result_536871090 = null;

  var F = {procname: "ex03_editable.connect", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/examples/ex03_editable.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 119;
    F.filename = "ex03_editable.nim";
    var start_536871091 = getRightAnchor_536870927(step1_536871088);
    F.line = 120;
    var ending_536871092 = getLeftAnchor_536870952(step2_536871089);
    F.line = 121;
    console.log(start_536871091);
    F.line = 122;
    console.log(ending_536871092);
    F.line = 125;
    var group_536871102 = new Konva.Group({x: toCdouble_1325400075(start_536871091.Field0), y: toCdouble_1325400075(start_536871091.Field1), width: toCdouble_1325400075(subInt(ending_536871092.Field0, start_536871091.Field0)), m_type: NTI1006632967, height: 0.0, draggable: false});
    F.line = 128;
    var circle1_536871103 = new Konva.Circle({x: 0.0, y: 0.0, radius: 6.0, stroke: "black", fill: "white", strokeWidth: 4, m_type: NTI1040187398});
    F.line = 130;
    var circle2_536871104 = new Konva.Circle({x: group_536871102.width(), y: 0.0, radius: 6.0, stroke: "black", fill: "white", strokeWidth: 4, m_type: NTI1040187398});
    F.line = 132;
    var arrow_536871109 = new Konva.Arrow({points: [6, 0, ((subInt(subInt(((group_536871102.width()) | 0), 6), 4)) | 0), 0], stroke: "black", strokeWidth: 4, pointerAtBeginning: false, pointerAtEnding: false, m_type: NTI1140850694, tension: 0, pointerLength: 0, pointerWidth: 0, fill: null});
    F.line = 134;
    group_536871102.add(circle1_536871103);
    F.line = 135;
    group_536871102.add(circle2_536871104);
    F.line = 136;
    group_536871102.add(arrow_536871109);
    F.line = 138;
    step1_536871088.outs.push(group_536871102);;
    F.line = 139;
    step2_536871089.ins.push(group_536871102);;
    F.line = 140;
    result_536871090 = group_536871102;
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_536871090;

}

function update_536871124(evt_536871125) {
  var F = {procname: "ex03_editable.update", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/examples/ex03_editable.nim", line: 0};
  framePtr = F;
    F.line = 150;
    F.filename = "ex03_editable.nim";
    var shape_536871129 = (evt_536871125.target);
    F.line = 151;
    var shapeX_536871130 = ((shape_536871129.x()) | 0);
    F.line = 152;
    var shapeY_536871131 = ((shape_536871129.y()) | 0);
    F.line = 153;
    var shapeWidth_536871132 = ((shape_536871129.width()) | 0);
    F.line = 154;
    var shapeHeight_536871133 = ((shape_536871129.height()) | 0);
    Label1: {
      F.line = 156;
      var arrowGroup_536871138 = null;
      F.line = 355;
      F.filename = "jsffi.nim";
      var colontmp__536871443 = null;
      F.line = 156;
      F.filename = "ex03_editable.nim";
      colontmp__536871443 = shape_536871129.ins;
      F.line = 357;
      F.filename = "jsffi.nim";
      var v_536871444 = null;
      F.line = 358;
      for (var k in colontmp__536871443) {
      F.line = 359;
        if (!colontmp__536871443.hasOwnProperty(k)) { continue; }
      F.line = 360;
        v_536871444 = colontmp__536871443[k];
      F.line = 156;
      F.filename = "ex03_editable.nim";
      arrowGroup_536871138 = v_536871444;
      F.line = 157;
      var myPoints_536871147 = arrowGroup_536871138.children[2].points();
      F.line = 158;
      var arrowX_536871152 = arrowGroup_536871138.x();
      F.line = 159;
      var arrowY_536871157 = arrowGroup_536871138.y();
      arrowGroup_536871138.children[1].y((shapeY_536871131));
      arrowGroup_536871138.children[1].x((subInt(((shapeX_536871130) | 0), ((shapeWidth_536871132) | 0))));
      arrowGroup_536871138.children[2].setPoints(([(myPoints_536871147[0]), (myPoints_536871147[1]), ((subInt(subInt(subInt(shapeX_536871130, shapeWidth_536871132), 6), 4)) | 0), ((shapeY_536871131) | 0)]));
      F.line = 362;
      F.filename = "jsffi.nim";
      }
    };
    Label2: {
      F.line = 169;
      F.filename = "ex03_editable.nim";
      var arrowGroup_536871219 = null;
      F.line = 355;
      F.filename = "jsffi.nim";
      var colontmp__536871446 = null;
      F.line = 169;
      F.filename = "ex03_editable.nim";
      colontmp__536871446 = shape_536871129.outs;
      F.line = 357;
      F.filename = "jsffi.nim";
      var v_536871447 = null;
      F.line = 358;
      for (var k in colontmp__536871446) {
      F.line = 359;
        if (!colontmp__536871446.hasOwnProperty(k)) { continue; }
      F.line = 360;
        v_536871447 = colontmp__536871446[k];
      F.line = 169;
      F.filename = "ex03_editable.nim";
      arrowGroup_536871219 = v_536871447;
      F.line = 171;
      var myPoints_536871228 = arrowGroup_536871219.children[2].points();
      arrowGroup_536871219.children[0].y((shapeY_536871131));
      arrowGroup_536871219.children[0].x((((shapeX_536871130) | 0)));
      arrowGroup_536871219.children[2].points(([((addInt(shapeX_536871130, 6)) | 0), ((shapeY_536871131) | 0), (myPoints_536871228[2]), (myPoints_536871228[3])]));
      F.line = 362;
      F.filename = "jsffi.nim";
      }
    };
  framePtr = F.prev;

  
}

function main_536871286() {
  var F = {procname: "ex03_editable.main", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/examples/ex03_editable.nim", line: 0};
  framePtr = F;
    F.line = 197;
    F.filename = "ex03_editable.nim";
    var stage_536871287 = new Konva.Stage(null);
    stage_536871287.container(("container"));
    stage_536871287.widht((1000));
    stage_536871287.heght((800));
    F.line = 201;
    var layer_536871321 = new Konva.Layer();
    F.line = 203;
    var step1_536871326 = newStep_536870961({n: 1, title: [82,101,113,117,101,115,116,32,115,117,112,112,111,114,116], by: [[67,117,115,116,111,109,101,114], [84,101,99,104,110,105,99,97,108,32,83,117,112,112,111,114,116]], m_type: NTI536870920, x: 0.0, y: 0.0, width: 0.0, height: 0.0, draggable: false});
    F.line = 204;
    var step2_536871331 = newStep_536870961({n: 2, title: [82,101,115,111,108,118,101,32,115,97,108,101,115,32,115,117,112,112,111,114,116,32,114,101,113,117,101,115,116], by: [[83,97,108,101,115]], x: 300.0, m_type: NTI536870920, y: 0.0, width: 0.0, height: 0.0, draggable: false});
    F.line = 205;
    var arrow_536871332 = connect_536871087(step1_536871326, step2_536871331);
    F.line = 206;
    step2_536871331.on("dragmove", update_536871124);
    F.line = 207;
    step1_536871326.on("dragmove", update_536871124);
    F.line = 208;
    layer_536871321.add(step1_536871326);
    F.line = 209;
    layer_536871321.add(step2_536871331);
    F.line = 210;
    layer_536871321.add(arrow_536871332);
    F.line = 233;
    stage_536871287.add(layer_536871321);
    F.line = 234;
    layer_536871321.draw();
    F.line = 236;
    console.log(getRightAnchor_536870927(step1_536871326));
  framePtr = F.prev;

  
}
var F = {procname: "module ex03_editable", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/examples/ex03_editable.nim", line: 0};
framePtr = F;
F.line = 238;
F.filename = "ex03_editable.nim";
main_536871286();
framePtr = F.prev;
var F = {procname: "module ex03_editable", prev: framePtr, filename: "/home/jose/Documentos/src/nimlang/konva.nim/examples/ex03_editable.nim", line: 0};
framePtr = F;
framePtr = F.prev;
