/* Generated by the Nim Compiler v2.0.14 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI1207959559 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI1207959558 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1107296262 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1342177319 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI1342177288 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33554466 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI1073741831 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1426063365 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI1426063364 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI721420294 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI721420293 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1090519044 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1073741830 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI1073741829 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI1073741827 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI1426063454 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI184549391 = {size: 0,kind: 36,base: null,node: null,finalizer: null};
var NTI1124073478 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555173 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555183 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI738197584 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI184549387 = {size: 0,kind: 34,base: null,node: null,finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI1191182346 = {size: 0, kind: 24, base: null, node: null, finalizer: null};
var NTI1191182345 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
NTI1191182346.base = NTI33554435;
var NNI1191182345 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "points", len: 0, typ: NTI1191182346, name: "points", sons: null}, 
{kind: 1, offset: "stroke", len: 0, typ: NTI33554450, name: "stroke", sons: null}, 
{kind: 1, offset: "strokeWidth", len: 0, typ: NTI184549387, name: "strokeWidth", sons: null}, 
{kind: 1, offset: "lineCap", len: 0, typ: NTI33554450, name: "lineCap", sons: null}, 
{kind: 1, offset: "lineJoin", len: 0, typ: NTI33554450, name: "lineJoin", sons: null}]};
NTI1191182345.node = NNI1191182345;
var NNI738197584 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI738197584.node = NNI738197584;
var NNI33555183 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555183.node = NNI33555183;
var NNI33555173 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555173.node = NNI33555173;
NTI33555183.base = NTI33555173;
NTI738197584.base = NTI33555183;
NTI1191182345.base = NTI738197584;
var NNI1124073478 = {kind: 2, len: 13, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "x", len: 0, typ: NTI184549391, name: "x", sons: null}, 
{kind: 1, offset: "y", len: 0, typ: NTI184549391, name: "y", sons: null}, 
{kind: 1, offset: "width", len: 0, typ: NTI184549391, name: "width", sons: null}, 
{kind: 1, offset: "height", len: 0, typ: NTI184549391, name: "height", sons: null}, 
{kind: 1, offset: "fill", len: 0, typ: NTI33554450, name: "fill", sons: null}, 
{kind: 1, offset: "stroke", len: 0, typ: NTI33554450, name: "stroke", sons: null}, 
{kind: 1, offset: "strokeWidth", len: 0, typ: NTI184549391, name: "strokeWidth", sons: null}, 
{kind: 1, offset: "cornerRadius", len: 0, typ: NTI184549391, name: "cornerRadius", sons: null}, 
{kind: 1, offset: "shadowColor", len: 0, typ: NTI33554450, name: "shadowColor", sons: null}, 
{kind: 1, offset: "shadowBlur", len: 0, typ: NTI184549387, name: "shadowBlur", sons: null}, 
{kind: 1, offset: "shadowOffsetX", len: 0, typ: NTI184549387, name: "shadowOffsetX", sons: null}, 
{kind: 1, offset: "shadowOffsetY", len: 0, typ: NTI184549387, name: "shadowOffsetY", sons: null}, 
{kind: 1, offset: "shadowOpacity", len: 0, typ: NTI184549391, name: "shadowOpacity", sons: null}]};
NTI1124073478.node = NNI1124073478;
NTI1124073478.base = NTI738197584;
var NNI1073741829 = {kind: 1, offset: "add", len: 0, typ: NTI1073741830, name: "add", sons: null};
NTI1073741829.node = NNI1073741829;
var NNI1090519044 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI1090519044.node = NNI1090519044;
var NNI721420293 = {kind: 1, offset: "on", len: 0, typ: NTI721420294, name: "on", sons: null};
NTI721420293.node = NNI721420293;
NTI721420293.base = NTI738197584;
NTI1090519044.base = NTI721420293;
NTI1073741829.base = NTI1090519044;
NTI1073741827.base = NTI1073741829;
NTI1426063454.base = NTI1073741827;
NTI1426063365.base = NTI33554450;
var NNI1426063364 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "n", len: 0, typ: NTI33554435, name: "n", sons: null}, 
{kind: 1, offset: "title", len: 0, typ: NTI33554450, name: "title", sons: null}, 
{kind: 1, offset: "by", len: 0, typ: NTI1426063365, name: "by", sons: null}]};
NTI1426063364.node = NNI1426063364;
var NNI1073741831 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "x", len: 0, typ: NTI184549391, name: "x", sons: null}, 
{kind: 1, offset: "y", len: 0, typ: NTI184549391, name: "y", sons: null}, 
{kind: 1, offset: "width", len: 0, typ: NTI184549391, name: "width", sons: null}, 
{kind: 1, offset: "height", len: 0, typ: NTI184549391, name: "height", sons: null}, 
{kind: 1, offset: "draggable", len: 0, typ: NTI33554466, name: "draggable", sons: null}]};
NTI1073741831.node = NNI1073741831;
NTI1073741831.base = NTI738197584;
NTI1426063364.base = NTI1073741831;
var NNI1342177288 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554435, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}]};
NTI1342177288.node = NNI1342177288;
var NNI1342177319 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554435, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}]};
NTI1342177319.node = NNI1342177319;
var NNI1107296262 = {kind: 2, len: 6, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "x", len: 0, typ: NTI184549391, name: "x", sons: null}, 
{kind: 1, offset: "y", len: 0, typ: NTI184549391, name: "y", sons: null}, 
{kind: 1, offset: "radius", len: 0, typ: NTI184549391, name: "radius", sons: null}, 
{kind: 1, offset: "fill", len: 0, typ: NTI33554450, name: "fill", sons: null}, 
{kind: 1, offset: "stroke", len: 0, typ: NTI33554450, name: "stroke", sons: null}, 
{kind: 1, offset: "strokeWidth", len: 0, typ: NTI184549387, name: "strokeWidth", sons: null}]};
NTI1107296262.node = NNI1107296262;
NTI1107296262.base = NTI738197584;
NTI1207959559.base = NTI184549387;
var NNI1207959558 = {kind: 2, len: 9, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "points", len: 0, typ: NTI1207959559, name: "points", sons: null}, 
{kind: 1, offset: "tension", len: 0, typ: NTI184549387, name: "tension", sons: null}, 
{kind: 1, offset: "pointerLength", len: 0, typ: NTI184549387, name: "pointerLength", sons: null}, 
{kind: 1, offset: "pointerWidth", len: 0, typ: NTI184549387, name: "pointerWidth", sons: null}, 
{kind: 1, offset: "pointerAtBeginning", len: 0, typ: NTI33554466, name: "pointerAtBeginning", sons: null}, 
{kind: 1, offset: "pointerAtEnding", len: 0, typ: NTI33554466, name: "pointerAtEnding", sons: null}, 
{kind: 1, offset: "fill", len: 0, typ: NTI33554450, name: "fill", sons: null}, 
{kind: 1, offset: "stroke", len: 0, typ: NTI33554450, name: "stroke", sons: null}, 
{kind: 1, offset: "strokeWidth", len: 0, typ: NTI184549387, name: "strokeWidth", sons: null}]};
NTI1207959558.node = NNI1207959558;
NTI1207959558.base = NTI738197584;

function mnewString(len_33557003) {
        var result = new Array(len_33557003);
    for (var i = 0; i < len_33557003; i++) {result[i] = 0;}
    return result;
  

  
}

function toJSStr(s_33556901) {
  var result_33556902 = null;

    var res_33556943 = newSeq_33556919((s_33556901).length);
    var i_33556944 = 0;
    var j_33556945 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556944 < (s_33556901).length)) break Label2;
          var c_33556946 = s_33556901[i_33556944];
          if ((c_33556946 < 128)) {
          res_33556943[j_33556945] = String.fromCharCode(c_33556946);
          i_33556944 += 1;
          }
          else {
            var helper_33556959 = newSeq_33556919(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556960 = c_33556946.toString(16);
                  if ((((code_33556960) == null ? 0 : (code_33556960).length) == 1)) {
                  helper_33556959.push("%0");;
                  }
                  else {
                  helper_33556959.push("%");;
                  }
                  
                  helper_33556959.push(code_33556960);;
                  i_33556944 += 1;
                  if ((((s_33556901).length <= i_33556944) || (s_33556901[i_33556944] < 128))) {
                  break Label3;
                  }
                  
                  c_33556946 = s_33556901[i_33556944];
                }
            };
++excHandler;
            try {
            res_33556943[j_33556945] = decodeURIComponent(helper_33556959.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556943[j_33556945] = helper_33556959.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556945 += 1;
        }
    };
    if (res_33556943.length < j_33556945) { for (var i = res_33556943.length ; i < j_33556945 ; ++i) res_33556943.push(null); }
               else { res_33556943.length = j_33556945; };
    result_33556902 = res_33556943.join("");

  return result_33556902;

}

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_33557268, src_33557269, ti_33557270) {
  var result_33557279 = null;

    switch (ti_33557270.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_33557259(ti_33557270))) {
      result_33557279 = src_33557269;
      }
      else {
        result_33557279 = [src_33557269[0], src_33557269[1]];
      }
      
      break;
    case 19:
            if (dest_33557268 === null || dest_33557268 === undefined) {
        dest_33557268 = {};
      }
      else {
        for (var key in dest_33557268) { delete dest_33557268[key]; }
      }
      for (var key in src_33557269) { dest_33557268[key] = src_33557269[key]; }
      result_33557279 = dest_33557268;
    
      break;
    case 18:
    case 17:
      if (!((ti_33557270.base == null))) {
      result_33557279 = nimCopy(dest_33557268, src_33557269, ti_33557270.base);
      }
      else {
      if ((ti_33557270.kind == 17)) {
      result_33557279 = (dest_33557268 === null || dest_33557268 === undefined) ? {m_type: ti_33557270} : dest_33557268;
      }
      else {
        result_33557279 = (dest_33557268 === null || dest_33557268 === undefined) ? {} : dest_33557268;
      }
      }
      nimCopyAux(result_33557279, src_33557269, ti_33557270.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_33557269)) { 
        if(dest_33557268 === null || dest_33557268 === undefined || dest_33557268.length != src_33557269.length) {
          dest_33557268 = new src_33557269.constructor(src_33557269);
        } else {
          dest_33557268.set(src_33557269, 0);
        }
        result_33557279 = dest_33557268;
      } else {
        if (src_33557269 === null) {
          result_33557279 = null;
        }
        else {
          if (dest_33557268 === null || dest_33557268 === undefined || dest_33557268.length != src_33557269.length) {
            dest_33557268 = new Array(src_33557269.length);
          }
          result_33557279 = dest_33557268;
          for (var i = 0; i < src_33557269.length; ++i) {
            result_33557279[i] = nimCopy(result_33557279[i], src_33557269[i], ti_33557270.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_33557269 === null) {
        result_33557279 = null;
      }
      else {
        if (dest_33557268 === null || dest_33557268 === undefined || dest_33557268.length != src_33557269.length) {
          dest_33557268 = new Array(src_33557269.length);
        }
        result_33557279 = dest_33557268;
        for (var i = 0; i < src_33557269.length; ++i) {
          result_33557279[i] = nimCopy(result_33557279[i], src_33557269[i], ti_33557270.base);
        }
      }
    
      break;
    case 28:
            if (src_33557269 !== null) {
        result_33557279 = src_33557269.slice(0);
      }
    
      break;
    default: 
      result_33557279 = src_33557269;
      break;
    }

  return result_33557279;

}
var objectID_805306545 = [0];

function addChars_301990090(result_301990092, result_301990092_Idx, x_301990093, start_301990094, n_301990095) {
    var Temporary1;

    var old_301990096 = (result_301990092[result_301990092_Idx]).length;
    if (result_301990092[result_301990092_Idx].length < (Temporary1 = (old_301990096 + n_301990095), Temporary1)) { for (var i = result_301990092[result_301990092_Idx].length; i < Temporary1; ++i) result_301990092[result_301990092_Idx].push(0); }
         else {result_301990092[result_301990092_Idx].length = Temporary1; };
    Label2: {
      var iHEX60gensym4_301990110 = 0;
      var i_553648317 = 0;
      Label3: {
          Label4: while (true) {
          if (!(i_553648317 < n_301990095)) break Label4;
            iHEX60gensym4_301990110 = i_553648317;
            result_301990092[result_301990092_Idx][(old_301990096 + iHEX60gensym4_301990110)] = x_301990093.charCodeAt((start_301990094 + iHEX60gensym4_301990110));
            i_553648317 += 1;
          }
      };
    };

  
}

function addChars_301990086(result_301990088, result_301990088_Idx, x_301990089) {
    addChars_301990090(result_301990088, result_301990088_Idx, x_301990089, 0, ((x_301990089) == null ? 0 : (x_301990089).length));

  
}

function addInt_301990111(result_301990112, result_301990112_Idx, x_301990113) {
    addChars_301990086(result_301990112, result_301990112_Idx, ((x_301990113) + ""));

  
}

function addInt_301990129(result_301990130, result_301990130_Idx, x_301990131) {
    addInt_301990111(result_301990130, result_301990130_Idx, BigInt(x_301990131));

  
}

function HEX24_369098760(x_369098761) {
  var result_369098762 = [[]];

    addInt_301990129(result_369098762, 0, x_369098761);

  return result_369098762[0];

}

function formatValue_1426063390(result_1426063393, result_1426063393_Idx, value_1426063394) {
    result_1426063393[result_1426063393_Idx].push.apply(result_1426063393[result_1426063393_Idx], HEX24_369098760(value_1426063394));;

  
}

function newSeq_33556919(len_33556921) {
  var result_33556922 = [];

    result_33556922 = new Array(len_33556921); for (var i = 0 ; i < len_33556921 ; ++i) { result_33556922[i] = null; }
  return result_33556922;

}

function isFatPointer_33557259(ti_33557260) {
  var result_33557261 = false;

  BeforeRet: {
    result_33557261 = !((ConstSet1[ti_33557260.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557261;

}

function nimCopyAux(dest_33557272, src_33557273, n_33557274) {
    switch (n_33557274.kind) {
    case 0:
      break;
    case 1:
            dest_33557272[n_33557274.offset] = nimCopy(dest_33557272[n_33557274.offset], src_33557273[n_33557274.offset], n_33557274.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_33557274.sons.length; i++) {
      nimCopyAux(dest_33557272, src_33557273, n_33557274.sons[i]);
    }
    
      break;
    case 3:
            dest_33557272[n_33557274.offset] = nimCopy(dest_33557272[n_33557274.offset], src_33557273[n_33557274.offset], n_33557274.typ);
      for (var i = 0; i < n_33557274.sons.length; ++i) {
        nimCopyAux(dest_33557272, src_33557273, n_33557274.sons[i][1]);
      }
    
      break;
    }

  
}

function newStep_1426063369(val_1426063370) {
  var result_1426063371 = null;

  BeforeRet: {
    var newVal_1426063372 = val_1426063370;
    if (!((0.0 < val_1426063370.width))) {
    newVal_1426063372.width = 200.0;
    }
    
    if (!(val_1426063370.draggable)) {
    newVal_1426063372.draggable = true;
    }
    
    var headerHeight_1426063373 = 50;
    var titleHeight_1426063374 = 100;
    var group_1426063375 = new Konva.Group(newVal_1426063372);
    var stepNumberH_1426063376 = 20;
    var stepNumber_1426063377 = new Konva.Text();
    stepNumber_1426063377.width(group_1426063375.width());
    Label1: {
      var fmtRes_1426063385 = [mnewString(0)];
      formatValue_1426063390(fmtRes_1426063385, 0, val_1426063370.n);
    };
    stepNumber_1426063377.text(toJSStr(fmtRes_1426063385[0]));
    stepNumber_1426063377.fontSize(25);
    stepNumber_1426063377.fontFamily("Calibri");
    stepNumber_1426063377.fill("darkgray");
    stepNumber_1426063377.align("left");
    stepNumber_1426063377.padding(10);
    group_1426063375.add(stepNumber_1426063377);
    var stepTitle_1426063396 = new Konva.Text();
    stepTitle_1426063396.width(group_1426063375.width());
    stepTitle_1426063396.text(val_1426063370.title);
    stepTitle_1426063396.fontSize(((stepNumberH_1426063376) | 0));
    stepTitle_1426063396.fontFamily("Arial");
    stepTitle_1426063396.fill("black");
    stepTitle_1426063396.align("center");
    stepTitle_1426063396.padding(10);
    stepTitle_1426063396.offsetY(((-(headerHeight_1426063373)) | 0));
    group_1426063375.add(stepTitle_1426063396);
    var actioneeH_1426063397 = 50;
    var n_1426063398 = 0;
    var h_1426063399 = (headerHeight_1426063373 + titleHeight_1426063374);
    Label2: {
      var actionee_1426063420 = null;
      var i_553648310 = 0;
      var L_553648311 = (val_1426063370.by).length;
      Label3: {
          Label4: while (true) {
          if (!(i_553648310 < L_553648311)) break Label4;
            actionee_1426063420 = val_1426063370.by[i_553648310];
            var line_1426063425 = new Konva.Line({points: [0, h_1426063399, ((group_1426063375.width()) | 0), h_1426063399], stroke: "black", strokeWidth: 1, m_type: NTI1191182345, lineCap: null, lineJoin: null});
            var actioneeTxt_1426063426 = new Konva.Text();
            actioneeTxt_1426063426.width(group_1426063375.width());
            actioneeTxt_1426063426.text(actionee_1426063420);
            actioneeTxt_1426063426.fontSize(20);
            actioneeTxt_1426063426.fontFamily("Arial");
            actioneeTxt_1426063426.fill("blue");
            actioneeTxt_1426063426.align("left");
            actioneeTxt_1426063426.padding(10);
            actioneeTxt_1426063426.offsetY(((-(h_1426063399)) | 0));
            h_1426063399 = (h_1426063399 + ((actioneeTxt_1426063426.height()) | 0));
            group_1426063375.add(line_1426063425);
            group_1426063375.add(actioneeTxt_1426063426);
            n_1426063398 += 1;
            i_553648310 += 1;
          }
      };
    };
    if (!((val_1426063370.height == 0.0))) {
    h_1426063399 = ((val_1426063370.height) | 0);
    }
    
    var rect_1426063431 = new Konva.Rect({width: group_1426063375.width(), height: h_1426063399, fill: "lightgray", stroke: "black", strokeWidth: 4.0, shadowBlur: 10, cornerRadius: 10.0, m_type: NTI1124073478, x: 0.0, y: 0.0, shadowColor: null, shadowOffsetX: 0, shadowOffsetY: 0, shadowOpacity: 0.0});
    group_1426063375.height(h_1426063399);
    group_1426063375.add(rect_1426063431);
    rect_1426063431.zIndex(0);
    var tmp_1426063432 = group_1426063375;
    tmp_1426063432.ins = nimCopy(null, [], NTI1426063454);
    tmp_1426063432.outs = nimCopy(null, [], NTI1426063454);
    result_1426063371 = tmp_1426063432;
    break BeforeRet;
  };

  return result_1426063371;

}

function getRightAnchor_1342177286(step_1342177287) {
  var result_1342177290 = {Field0: 0, Field1: 0};

  BeforeRet: {
    var w_1342177291 = step_1342177287.width();
    var h_1342177292 = step_1342177287.height();
    h_1342177292 = 150.0;
    var x_1342177293 = step_1342177287.x();
    var y_1342177294 = step_1342177287.y();
    var colontmp__553648321 = (((x_1342177293 + w_1342177291)) | 0);
    var colontmp__553648322 = (((y_1342177294 + (h_1342177292 / 2.0))) | 0);
    result_1342177290 = nimCopy(result_1342177290, {Field0: colontmp__553648321, Field1: colontmp__553648322}, NTI1342177288);
    break BeforeRet;
  };

  return result_1342177290;

}

function getLeftAnchor_1342177344(step_1342177345) {
  var result_1342177348 = {Field0: 0, Field1: 0};

  BeforeRet: {
    var w_1342177349 = step_1342177345.width();
    var h_1342177350 = step_1342177345.height();
    h_1342177350 = 150.0;
    var x_1342177351 = step_1342177345.x();
    var y_1342177352 = step_1342177345.y();
    var colontmp__553648323 = ((x_1342177351) | 0);
    var colontmp__553648324 = (((y_1342177352 + (h_1342177350 / 2.0))) | 0);
    result_1342177348 = nimCopy(result_1342177348, {Field0: colontmp__553648323, Field1: colontmp__553648324}, NTI1342177319);
    break BeforeRet;
  };

  return result_1342177348;

}

function toCdouble_1392508939(val_1392508941) {
  var result_1392508942 = 0.0;

    result_1392508942 = val_1392508941;

  return result_1392508942;

}

function connect_1392508933(step1_1392508934, step2_1392508935) {
  var result_1392508936 = null;

  BeforeRet: {
    var start_1392508937 = getRightAnchor_1342177286(step1_1392508934);
    var ending_1392508938 = getLeftAnchor_1342177344(step2_1392508935);
    console.log(start_1392508937);
    console.log(ending_1392508938);
    var group_1392508949 = new Konva.Group({x: toCdouble_1392508939(start_1392508937.Field0), y: toCdouble_1392508939(start_1392508937.Field1), width: toCdouble_1392508939((ending_1392508938.Field0 - start_1392508937.Field0)), m_type: NTI1073741831, height: 0.0, draggable: false});
    var circle1_1392508950 = new Konva.Circle({x: 0.0, y: 0.0, radius: 6.0, stroke: "black", fill: "white", strokeWidth: 4, m_type: NTI1107296262});
    var circle2_1392508951 = new Konva.Circle({x: group_1392508949.width(), y: 0.0, radius: 6.0, stroke: "black", fill: "white", strokeWidth: 4, m_type: NTI1107296262});
    var arrow_1392508956 = new Konva.Arrow({points: [6, 0, ((((((group_1392508949.width()) | 0) - 6) - 4)) | 0), 0], stroke: "black", strokeWidth: 4, pointerAtBeginning: false, pointerAtEnding: false, m_type: NTI1207959558, tension: 0, pointerLength: 0, pointerWidth: 0, fill: null});
    group_1392508949.add(circle1_1392508950);
    group_1392508949.add(circle2_1392508951);
    group_1392508949.add(arrow_1392508956);
    step1_1392508934.outs.push(group_1392508949);;
    step2_1392508935.ins.push(group_1392508949);;
    result_1392508936 = group_1392508949;
    break BeforeRet;
  };

  return result_1392508936;

}

function update_1375731719(evt_1375731720) {
    var shape_1375731724 = (evt_1375731720.target);
    var shapeX_1375731725 = ((shape_1375731724.x()) | 0);
    var shapeY_1375731726 = ((shape_1375731724.y()) | 0);
    var shapeWidth_1375731727 = ((shape_1375731724.width()) | 0);
    var shapeHeight_1375731728 = ((shape_1375731724.height()) | 0);
    Label1: {
      var arrowGroup_1375731742 = null;
      var colontmp__553648326 = null;
      colontmp__553648326 = shape_1375731724.ins;
      var v_553648327 = null;
      for (var k in colontmp__553648326) {
        if (!colontmp__553648326.hasOwnProperty(k)) { continue; }
        v_553648327 = colontmp__553648326[k];
      arrowGroup_1375731742 = v_553648327;
      var myPoints_1375731755 = arrowGroup_1375731742.children[2].points();
      var arrowX_1375731760 = arrowGroup_1375731742.x();
      var arrowY_1375731765 = arrowGroup_1375731742.y();
      arrowGroup_1375731742.children[1].y((shapeY_1375731726));
      arrowGroup_1375731742.children[1].x(((((shapeX_1375731725) | 0) - ((shapeWidth_1375731727) | 0))));
      arrowGroup_1375731742.children[2].setPoints(([(myPoints_1375731755[0]), (myPoints_1375731755[1]), (((((shapeX_1375731725 - shapeWidth_1375731727) - 6) - 4)) | 0), ((shapeY_1375731726) | 0)]));
      }
    };
    Label2: {
      var arrowGroup_1375731827 = null;
      var colontmp__553648329 = null;
      colontmp__553648329 = shape_1375731724.outs;
      var v_553648330 = null;
      for (var k in colontmp__553648329) {
        if (!colontmp__553648329.hasOwnProperty(k)) { continue; }
        v_553648330 = colontmp__553648329[k];
      arrowGroup_1375731827 = v_553648330;
      var myPoints_1375731836 = arrowGroup_1375731827.children[2].points();
      arrowGroup_1375731827.children[0].y((shapeY_1375731726));
      arrowGroup_1375731827.children[0].x((((shapeX_1375731725) | 0)));
      arrowGroup_1375731827.children[2].points(([(((shapeX_1375731725 + 6)) | 0), ((shapeY_1375731726) | 0), (myPoints_1375731836[2]), (myPoints_1375731836[3])]));
      }
    };

  
}

function main_553648133() {
    
function innerHEX60gensym8_553648146() {
      var result_553648147 = null;

      BeforeRet: {
        var a_553648148 = null;
        a_553648148 = {};
        a_553648148.container = "container";
        a_553648148.width = "1000";
        a_553648148.height = "800";
        result_553648147 = a_553648148;
        break BeforeRet;
      };

      return result_553648147;

    }

    var stage_553648194 = new Konva.Stage(innerHEX60gensym8_553648146());
    var layer_553648195 = new Konva.Layer();
    var step1_553648200 = newStep_1426063369({n: 1, title: "Request support", by: ["Customer", "Technical Support"], m_type: NTI1426063364, x: 0.0, y: 0.0, width: 0.0, height: 0.0, draggable: false});
    var step2_553648205 = newStep_1426063369({n: 2, title: "Resolve sales support request", by: ["Sales"], x: 300.0, m_type: NTI1426063364, y: 0.0, width: 0.0, height: 0.0, draggable: false});
    var arrow_553648206 = connect_1392508933(step1_553648200, step2_553648205);
    step2_553648205.on("dragmove", update_1375731719);
    step1_553648200.on("dragmove", update_1375731719);
    layer_553648195.add(step1_553648200);
    layer_553648195.add(step2_553648205);
    layer_553648195.add(arrow_553648206);
    stage_553648194.add(layer_553648195);
    layer_553648195.draw();
    console.log(getRightAnchor_1342177286(step1_553648200));

  
}
main_553648133();
