/* Generated by the Nim Compiler v2.0.14 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var objectID_788529329 = [0];

function main_553648133() {
    
function innerHEX60gensym8_553648146() {
      var result_553648147 = null;

      BeforeRet: {
        var a_553648148 = null;
        a_553648148 = {};
        a_553648148.container = "container";
        a_553648148.width = "1000";
        a_553648148.height = "800";
        result_553648147 = a_553648148;
        break BeforeRet;
      };

      return result_553648147;

    }

    var stage_553648203 = new Konva.Stage(innerHEX60gensym8_553648146());
    var layer_553648204 = new Konva.Layer();
    var txt1_553648205 = new Konva.Text();
    txt1_553648205.text("COMPLEX TEXT\nll the world's a stage, and all the men and women merely players. They have their exits and their entrances.");
    txt1_553648205.offsetX((-20));
    txt1_553648205.offsetY((-20));
    txt1_553648205.name("red");
    txt1_553648205.addName("selected");
    console.log(txt1_553648205.name());
    txt1_553648205.align("center");
    console.log(txt1_553648205.align());
    txt1_553648205.alpha(0.7);
    txt1_553648205.blue(255);
    txt1_553648205.width("auto");
    console.log(txt1_553648205.width());
    txt1_553648205.x(100.5);
    txt1_553648205.y(50.3);
    console.log(txt1_553648205.text());
    console.log(txt1_553648205.offsetX());
    layer_553648204.add(txt1_553648205);
    stage_553648203.add(layer_553648204);
    layer_553648204.draw();

  
}
main_553648133();
