/* Generated by the Nim Compiler v2.0.14 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33555173 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555183 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI721420368 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI184549387 = {size: 0,kind: 34,base: null,node: null,finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI184549391 = {size: 0,kind: 36,base: null,node: null,finalizer: null};
var NTI1090519046 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI1090519046 = {kind: 2, len: 6, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "x", len: 0, typ: NTI184549391, name: "x", sons: null}, 
{kind: 1, offset: "y", len: 0, typ: NTI184549391, name: "y", sons: null}, 
{kind: 1, offset: "radius", len: 0, typ: NTI184549391, name: "radius", sons: null}, 
{kind: 1, offset: "fill", len: 0, typ: NTI33554450, name: "fill", sons: null}, 
{kind: 1, offset: "stroke", len: 0, typ: NTI33554450, name: "stroke", sons: null}, 
{kind: 1, offset: "strokeWidth", len: 0, typ: NTI184549387, name: "strokeWidth", sons: null}]};
NTI1090519046.node = NNI1090519046;
var NNI721420368 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI721420368.node = NNI721420368;
var NNI33555183 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555183.node = NNI33555183;
var NNI33555173 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555173.node = NNI33555173;
NTI33555183.base = NTI33555173;
NTI721420368.base = NTI33555183;
NTI1090519046.base = NTI721420368;
var objectID_788529329 = [0];

function main_553648131() {
    
function innerHEX60gensym8_553648144() {
      var result_553648145 = null;

      BeforeRet: {
        var a_553648146 = null;
        a_553648146 = {};
        a_553648146.container = "container";
        a_553648146.width = "500";
        a_553648146.height = "500";
        result_553648145 = a_553648146;
        break BeforeRet;
      };

      return result_553648145;

    }

    var stage_553648201 = new Konva.Stage(innerHEX60gensym8_553648144());
    var layer_553648202 = new Konva.Layer();
    var circle_553648203 = new Konva.Circle({x: (stage_553648201.width() / 2.0), y: (stage_553648201.height() / 2.0), radius: 70.0, fill: "red", stroke: "black", strokeWidth: 4, m_type: NTI1090519046});
    circle_553648203.cache();
    circle_553648203.filters(([Konva.Filters.Blur]));
    circle_553648203.blurRadius(10);
    layer_553648202.add(circle_553648203);
    stage_553648201.add(layer_553648202);

  
}
main_553648131();
